CREATE DATABASE IF NOT EXISTS test;
USE test;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT (11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR (20) DEFAULT NULL,
  `sex` INT (1) NOT NULL DEFAULT '0',
  `age` INT (1) NOT NULL DEFAULT '0',
  `description` VARCHAR (240) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;
CREATE TABLE `count` (
  `uid` INT (11) NOT NULL,
  `fans` INT (1) NOT NULL DEFAULT '0',
  `follows` INT (1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;
